### ISSUE TITLE
Create system for managing/loading common configurations

### ISSUE THREAD

**Issue by samkohn** [samkohn/larpix-control#12]
Common configurations such as the pixel thresholds for each chip, the various test modes, etc. should be saveable and retrievable.

**Comment by peter-madigan** [comment]
I've started on this using python's ConfigParser. Let me know if you think I should use something else.

**Comment by samkohn** [comment]
I was actually thinking of using pyYAML because it's more portable and flexible.

**Comment by samkohn** [comment]
Satisfied with PR #14
