### ISSUE TITLE
Make scripts for the LArPix bench tests

### ISSUE THREAD

**Issue by samkohn** [samkohn/larpix-control#19]
List of tests is here: https://docs.google.com/a/lbl.gov/spreadsheets/d/1lyMwuWUwHIkaAFMlbA5xpFCMzlvWNo5SM7Jg9KSf7nk/edit?usp=sharing

**Comment by samkohn** [comment]
@peter-madigan If you want to work on this too we can split up the tests. Let me know

**Comment by peter-madigan** [comment]
I can definitely do some, I probably won't be able to get to it until Monday though.

**Comment by samkohn** [comment]
Cool thanks. I'll save 4.1, and 4.2 for you.
