### ISSUE TITLE
Serial reads sometimes include old data

### ISSUE THREAD

**Issue by samkohn** [samkohn/larpix-control#28]
When looping through a bunch of configurations, there are often packets from the previous configuration that are included in the `controller.run` output from the next configuration.

This appears to be an issue with flushing/emptying all of the buffers, from the LArPix onboard buffer all the way to the computer's serial buffer.

**Comment by peter-madigan** [comment]
Does this still occur with a `controller.serial_flush()` in between each write?

**Comment by samkohn** [comment]
Fixed in 78e5617db4c539f83e6f617989065bca467d6047 by adjusting the SerialPort.keep_open flag. Serial port should be closed between runs.
