### ISSUE TITLE
Create a way to interpret config read packets

### ISSUE THREAD

**Issue by peter-madigan** [samkohn/larpix-control#32]
There should be a method of creating a Configuration object from read packets - this will make tests that compare configuration values to ADC counts/trigger rate/etc easier to interpret.

**Comment by samkohn** [comment]
Implemented this in branch samkohn/sync-configuration, commit 7bcf60a. This will require thorough unit tests before I'd feel comfortable merging it in. It's a little bit terrible but also a little elegant.

**Comment by samkohn** [comment]
Closed with #43
